name: Build Check # Needed for security reasons

on:
  pull_request:
  push:
    branches:
      - 'main'

permissions: {}

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    services:
      # Required to build Prisma
      postgres:
        image: postgres
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://user:password@localhost:5432/db
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build ARABot
        run: |
          pnpm i
          pnpm exec prisma generate
          pnpm dlx prisma migrate deploy
          pnpm run cleanBuild
